name: Generate Release Archives

on:
  push:
    tags:
      - "v*"

# Sets permissions of the GITHUB_TOKEN to allow releases
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Generate Theme Archives
        run: python generate.py <<< "2"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          prerelease: false
          files: build/*.zip
